---
title: "Tissue removal"
---

### Materials

-   [ ] SCUBA tank and air gun
-   [ ] Zip-lock bags
-   [ ] Icebox with ice
-   [ ] SSW
-   [ ] Tissue homogenizer
-   [ ] 500 mL beaker
-   [ ] Scale
-   [ ] 12x 50 mL tubes (2 sets of 6)
-   [ ] 1000 µL pipette and tips without filter (3 tips per sample)
-   [ ] Vortexter
-   [ ] Ethanol 96% or 70% for cleaning
-   [ ] Centrifuge with rotor 19776
-   [ ] Aluminium foil
-   [ ] Eppendrof tubes (2 per sample) & rack

### Method

::: callout-note
Work in batches of six samples at a time.
:::

1.  Turn on centrifuge so it has enough time to cool down to 4°C.

2.  Transfer coral fragment into zip-lock bag and add enough SSW to immerse sample. Use an air gun to remove all coral tissue. Afterwards, the white coral skeleton should be visible. Rinse bag with with as little SSW as possible. Bags can be reused when cleaned properly.

3.  Store the skeleton in original sample bag in -20°C freezer until surface measurement.

4.  Transfer tissue slurry into a pre-weighted (taraed) 500 mL beaker. Note the weight to estimate the volume of the tissue slurry (`w_slurry1` in metadata sheet). This will be used to estimate the total volume of the tissue slurry.

5.  Homogenize tissue slurry for 40 s. Clean homogenizer by runing it in beaker filled with SSW and wipe dry between samples. After use, clean homogenizer by running it in freshwater.

6.  Immediately transfer 40 g tissue slurry into pre-weigh (taraed) 50 mL tube (note as `w_slurry2` in metadata sheet). Try to be exact to keep the centrifuge used later balanced. Store tubes with tissue slurry in fridge when preparing the remaining samples.

7.  Centrifuge the 6 50 mL-sample tubes using rotor 19676 for 20 min at 12,000 rpm at 4 °C. This separates the symbionts (pellet) from the host tissue (supernatant).

8.  With a 1000 mL pipette, remove as much supernatant as possible without damaging the pellet. Vortex to re-suspend remaining tissue slurry.

9.  Centrifuge for 10 min with the other settings as in step 6. Repeat steps 6 - 7 until all supernatant is be removed.

10. Add 3 mL SSW (1 mL pipette, tip can be re-used when not immersed) to all tubes and vortex until solution is homogeneous.

11. Divide solution for chlorophyll analysis (1 mL) and Symbiodiniaceae counts (1 mL) into Eppendorf tubes. Before pipetting, move liqid in pipette up and down to homogenise solution even more. Store all samples at 4°C, keep chlorophyll samples wrapped in aluminium foil. Start chlorophyll extraction at the same day.
