---
title: "Surface area"
---

### Overview

The chlorophyll concentration and Symbiodiniaceae counts have to be normalized to the coral surface (living tissue). The surface area is estimated with the difference of the weight of the coral fragment before and after immersion in paraffin wax. Each sample is immersed two times in the wax: the first time to close all pores and the second time for the actual surface estimation. Each time, wax at parts without tissue (the cut sides) have to be scratched off. The tissue surface is estimated with conversion factors based on custom-made calibration blocks (see [here](calibration.qmd){target="_blank"} for more info) with the formula

$$
A = 0.52 + 43.6 * \Delta w
$$

, where $A$ is the surface area in $cm^2$ and $\Delta w$ the the increase in weight in g between the first and second immersion.

Alternatively, the conversion factor in @veal2010 can be used:

$$
A = 34.32 * \Delta w
$$

### Materials

-   [ ] Yarn
-   [ ] Paper for labels
-   [ ] Scale
-   [ ] Paraffin dispenser with paraffin wax

### Method

1.  Attach yarn to coral fragment, keep one end with a length of ca. 15 cm.

2.  Attach paper label with sample ID to yarn.

3.  Weight fragment and note as `w_initial` in metadata sheet.

4.  Heat the paraffin dispenser (SELECTA) to 63°C (takes about 40 min). Stir and make sure that the paraffin wax is completely melted. Keep the left dial (regulates the temperature when removing the wax at low position). Refer to the [manual](manuals/paraffin_dispenser_068646_ME.pdf){target="_blank"} to refill paraffin wax.

5.  Dip in the fragment for 2 s.

6.  After removal, rotate sample by turning the yarn for about 3 s.

7.  Let the wax cool down for at least 15 min, weight, and note as `w1` in metadata sheet.

8.  Use fingernails to scratch off parts without tissue (edges where fragment was cut), weight, and not as `w1_scratched`.

9.  Repeat steps 5 to 7 and note weight as `w2` and `w2_scratched`.
