project:
  type: website

  
website:
  search: false
  title: ""
  favicon: images/logo.png
  page-footer: 
    left: "by Andreas Eich"
    right: "Version from 20.12.2024"
  sidebar:
    title: "CORAL protocols"
    background: light
    logo: images/logo.png
    style: "docked"
    collapse-level: 4
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Steps"
        contents: 
        - text: "Tissue removal"
          href: 1_tissue_removal.qmd
        - text: "Chlorophyll"
          href: 2_chlorophyll.qmd
        - text: "Counts"
          href: 3_symb_counts.qmd
        - text: "Area"
          href: 4_area.qmd
      - text: "Metadata"
        href: 5_metadata.qmd
      - text: "Calculations"
        href: 6_calculations.qmd
format:
  html:
    output-dir: _site
    theme: [lux, style/style.css]
    toc: true
    toc-depth: 4
    toc-title: "On this page"
    toc-location: right
    smooth-scroll: true
    
  pdf:
    fig-pos: 'h'
    tab-pos: 'h'
    output-dir: pdf_output
    papersize: "A4"
    geometry:
      - top=15mm
      - left=15mm
      - right=15mm
      - bottom=15mm
    toc: false
    number-sections: false
    colorlinks: true
    # Custom fonts
    mainfont: "Linux Libertine O"
    fontsize: "10pt"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "Noto Sans"
    mathfont: "Libertinus Math"
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
        dpi: 300

editor: visual
bibliography: bib/references.bib
csl: bib/apa.csl
